"""first seed

Revision ID: 504fe2f80ac4
Revises: 
Create Date: 2023-07-07 11:24:55.359737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504fe2f80ac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('reviews', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('reviews'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=False),
    sa.Column('preparation', sa.String(), nullable=False),
    sa.Column('tips', sa.String(), nullable=True),
    sa.Column('reviews', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredients'),
    sa.UniqueConstraint('picture'),
    sa.UniqueConstraint('preparation'),
    sa.UniqueConstraint('reviews'),
    sa.UniqueConstraint('tips'),
    sa.UniqueConstraint('title')
    )
    op.create_table('category_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_recipes_category_id_categories')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_category_recipes_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_recipes')
    op.drop_table('recipes')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
